#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

PACKAGE_JSON="package.json"
PACKAGE_LOCK_JSON="package-lock.json"

VERSION=$(grep '"version"' $PACKAGE_JSON | awk -F '"' '{print $4}')
MAJOR=$(echo $VERSION | awk -F '.' '{print $1}')
MINOR=$(echo $VERSION | awk -F '.' '{print $2}')
NEW_VERSION="$MAJOR.$((MINOR + 1)).0"

# Update package.json
sed -i "s/\"version\": \"$VERSION\"/\"version\": \"$NEW_VERSION\"/" $PACKAGE_JSON

# Update package-lock.json
sed -i "s/\"version\": \"$VERSION\"/\"version\": \"$NEW_VERSION\"/" $PACKAGE_LOCK_JSON

# Stage both files
git add $PACKAGE_JSON $PACKAGE_LOCK_JSON

echo "Version bumped to $NEW_VERSION and staged in package.json and package-lock.json."
